system-name:
 mysql

server:
 #运行端口
 port: 8763
spring:
 application:
  name: app-${system-name}
 datasource:
  driver-class-name : com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3307/savi-sys?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: 1234
eureka:
 instance:
  #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
  lease-renewal-interval-in-seconds: 5
  #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
  lease-expiration-duration-in-seconds: 10
  metadata-map:
   company-name: eureka
 client:
  #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
  registry-fetch-interval-seconds: 30
  serviceUrl:
   #服务注册地址
   defaultZone: http://localhost:8788/eureka/

mybatis:
 mapper-locations: classpath:Mapper/*.xml